### ISSUE TITLE
Smithscript Scaling 1.12.3

### ISSUE THREAD

**Issue by PercMain** [ThomasJClark/elden-ring-weapon-calculator#42]
Patch 1.12.3 removed (or at least lessened) the physical damage scaling from faith/Int on smithscript weapons with elemental affinities. The calculator says my Smithscript greathammer should be getting 414 physical damage but in game I get 340.

stats: 20 Str, 16 dex, 33 Int, 32 fai, 7 arc 

2 handed, +25, flame art

also thanks for this calculator, it’s hugely helpful!

**Comment by ThomasJClark** [comment]
Hi, thanks for the heads up. I'll check to make sure the data for 1.12.3 was imported correctly

**Comment by ThomasJClark** [comment]
Looks like the nerf was applied by adding a hidden E scaling for physical damage from int/fai on these weapons, rather than by changing the actual scaling of the weapon

Hidden scaling values are used all the time for AoWs (e.g. to make laser beams scale highly with int) but never before for basic attack power, so the calculator didn't check them before

**Comment by PercMain** [comment]
Interesting, i wonder why they did it that way instead of copying whatever method they use on the Erdsteel Dagger or Clayman's Harpoon

**Comment by ThomasJClark** [comment]
thanks again for the report, this has been fixed in 3cf06bb44222d8ff93bea1774f9975f67d9d7e96

![image](https://github.com/ThomasJClark/elden-ring-weapon-calculator/assets/3964980/d5e7d8e0-1698-4a1a-b545-d216871509fc)

**Comment by PercMain** [comment]
Awesome thank you!
