### ISSUE TITLE
Tool is great, but room for improvement

### ISSUE THREAD

**Issue by ThunderMage** [ThomasJClark/elden-ring-weapon-calculator#43]
First of all thank you for what you've provided us with. I have a couple suggestions to make it better:

1. Weapon links should go to the fextralife wiki instead of the fandom wiki.

2. Include weapon weight as a displayed stat, I think that's an important distinction to help rationalize their offensive stat differences. In a perfect world weapon length could be included as well, but that's too demanding of a request.

Have a nice day.

**Comment by 2mg** [comment]
To add to this - add buffs like Bloodflame Blade or Seppuku Ash of War into calculations.

**Comment by ThomasJClark** [comment]
> Weapon links should go to the fextralife wiki instead of the fandom wiki.

I'll probably switch to [Eldenpedia](https://eldenring.wiki.gg/wiki/Eldenpedia) once they have the DLC weapons, since fandom (the host, not the Elden Ring wiki) has gotten pretty bad

fextra is notoriously inaccurate, they use AI generated fake articles to rank higher and faster in search results, and they've been caught viewbotting and manipulating online communities that mention competitors 

> Include weapon weight as a displayed stat, I think that's an important distinction to help rationalize their offensive stat differences. In a perfect world weapon length could be included as well, but that's too demanding of a request.

#2
